### ISSUE TITLE
j.sal.ubuntu has unused variable called installedpackage_names

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_libs#1]
There is a variable called  installedpackage_names wich i think used for storing installed packages not used in Ubuntu SAL
https://github.com/threefoldtech/jumpscaleX_libs/blob/master/JumpscaleLibs/sal/ubuntu/Ubuntu.py#L14

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/jumpscaleX_libs/commit/7247694ae145d41a3a051cf1eb3b6f1e3cc34bad

**Comment by hossnys** [comment]
verified  on branch development
