### ISSUE TITLE
Support atomicswap for ethereum using threefoldtech/atomicswap/cmd/ethatomicswap

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscaleX_libs#10]
Support atomic swap with Ethereum using <https://github.com/threefoldtech/atomicswap/tree/master/cmd/ethatomicswap>, similar to how we already support BTC Electrum and TFT.

**Comment by rkhamis** [comment]
obsolete

**Comment by GlenDC** [comment]
👍
