### ISSUE TITLE
Add methods to calculate amount of resources used by reservation, and how much to pay each farm

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/jumpscaleX_libs#106]
in the [zosv2 SAL](https://github.com/threefoldtech/jumpscaleX_libs/tree/development_chat_reservation/JumpscaleLibs/sal/zosv2), public methods should be added to:

- Calculate how much resources (SRU,MRU,HRU, CRU) are going to be used by a reservation, per farm (and in total?).
- Based on the above, caluclate how much tft need to be payed per farm.

[This zos pr shows how to convert a reservation workload to resources](https://github.com/threefoldtech/zos/pull/540), see the file
 pkg/provision/resource_units.go

The reservation object is defined here: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/workloads/models/tfgrid_workloads_reservation_1.toml

**Comment by zaibon** [comment]
We have an open PR for everything related to the zosv2 SAL: https://github.com/threefoldtech/jumpscaleX_libs/pull/101

**Comment by LeeSmet** [comment]
Closed by #101
