### ISSUE TITLE
jsx tfchain client lists available outputs that are actually spent

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscaleX_libs#11]
need to investigate why and fix it

**Comment by GlenDC** [comment]
An example output is `7758038b91239101aaa72b865934bbbdf4268766508f47258145307b8a38e826`, it is returned properly as spent via <https://explorer.threefoldtoken.com/explorer/hashes/014ab1cf49a331bef9225a51a68623daf7e112fce0e81a91194a7f4fe7af1d9a793bc52d4676d0> (as it returns 2 references to it), but it still is part of available outputs in our JSX Tfchain wallet balance object. So it seems we parse that part incorrectly.

**Comment by serboctor** [comment]
Blocked on https://github.com/threefoldtech/rivine/issues/526, waiting for testnet update to verify. 
block

**Comment by GlenDC** [comment]
Verified and resolved.
