### ISSUE TITLE
Threebot proxy need to be updated

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_libs#116]
When I tried to login using 3bot, I got this error.

https://github.com/threefoldtech/jumpscaleX_libs/blob/master/JumpscaleLibs/tools/threebot_proxy/threebot_proxy.py#L56

![image](https://user-images.githubusercontent.com/41957921/76392885-20c30380-637b-11ea-8c33-d92106f0acd8.png)

**Comment by rkhamis** [comment]
done on unstable branch
