### ISSUE TITLE
Create reservation on both IPv6 and IPv4 nodes using Chatflow tool

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_libs#117]
[Chatflow](https://github.com/threefoldtech/jumpscaleX_libs/blob/development_tfchatflows/JumpscaleLibs/sal/chatflow/Chatflow.py) needs to be updated to handle creation of reservations on IPv6 nodes where an IPv4 node will act as a gateway between the user and the IPv6 node when the user doesn't have IPv4

**Comment by ranatrk** [comment]
The following scenario is added:
If the selected node(randomly selected from nodes available) is IPv6 and the user chooses to access using option IPv4 then an IPv4 node is chosen and added as a gateway between the user and the selected node. In that case the gateway Ipv4 node is added as well to the network and add_access is done on that node rather than the selected node such as in the other scenarios. Hence the user will be contacting the IPv4 node which will connect it to the IPv6 node

https://github.com/threefoldtech/jumpscaleX_libs/commit/46a6b1e43155b61d2a0d69a7b202b1622e71ae97#diff-421b65fa2dfa8837ab9569b97e6eeef1
https://github.com/threefoldtech/jumpscaleX_libs/commit/1a2494e328ba995913b7114d0d4c5d47865bc5c7#diff-421b65fa2dfa8837ab9569b97e6eeef1

**Comment by john-kheir** [comment]
for this specific issue, it is resolved. but still the chat flow has this issue https://github.com/threefoldtech/jumpscaleX_threebot/issues/434 .. so closing this but chatflow is not complete
