### ISSUE TITLE
qr code support in jsx

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_libs#134]
- [ ] choose lightweight library
- [ ] easy dsl to generate QR codes as files or as base64 to be embedded directly in the chatflow

**Comment by hossnys** [comment]
verified on unstable :
```
JSX> j.tools.qrcode.base64_get("samir1.3bot")                                                                                                                                                               
'iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQAAAAB/n//CAAAAk0lEQVR4nGP4DwQNDJjkB+E97A0M36/Ifm9g+BLbKg4kA1VBZNhRIPn9Wi5Q/INoCFDN/z/9QPX/7qupNzD8sdI83sDwUerVcqDKhR35DQw/gx4CVf57fwYo8lXYBaj3V+kmoMhHmQNA9v/v4kBdH+RK04F
m3nIHmR9ToA+yRRpERteYA8XvvNgPVCOt9xybO8EkAE3NanomFg8oAAAAAElFTkSuQmCC'
```

```
JSX> j.tools.qrcode.png_get("samir1.3bot","/sandbox/code/qr-test.png")   

```
![Screenshot from 2020-03-24 18-12-58](https://user-images.githubusercontent.com/26298009/77449722-fbaea600-6dfa-11ea-8df3-5825f8bb339e.png)

```
j.tools.qrcode.svg_get("samir1.3bot","/sandbox/code/qr-test.svg")

```
![Screenshot from 2020-03-24 19-02-50](https://user-images.githubusercontent.com/26298009/77454886-d40f0c00-6e01-11ea-8608-068c70abb585.png)

![photo_2020-03-24_18-18-58](https://user-images.githubusercontent.com/26298009/77450267-b50d7b80-6dfb-11ea-9199-7b2be2fbfd0e.jpg)
