### ISSUE TITLE
numbered goldchain tests no longer pass

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscaleX_libs#14]
Problem is with how factory classes work different now. Get used to be able to work different than they used to do. On top of that it seems that these clients now autosave, so sequential tests no longer start with a clean state.

Run:

```shell
kosmos 'j.clients.goldchain.test()'
```

What you'll see:

```
Thu 12 14:09:51 JSBase.py            - 141 - jumpscale.goldchain.wallet         : ***CLASS INIT 1: jsxobject2
FALLBACK REPLACE:    {'name': 'mywallet'}.{RESET}
FALLBACK REPLACE:    {'name': 'mywallet'}.{RESET}

*** file: /sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py
*** function: log2str [linenr:1962]


In [1]:    
```

Normally you would see the same as you see in https://github.com/threefoldtech/jumpscaleX_libs/issues/13 but i tried to fix it by destroying the client every test at start (but probably that is not a correct approach). I also replaced some new calls with gets and vica versa.

**Comment by GlenDC** [comment]
This is about the tests that live under: https://github.com/threefoldtech/jumpscaleX_libs/tree/development_stabilize/JumpscaleLibs/clients/goldchain/tests

**Comment by serboctor** [comment]
Related to https://github.com/threefoldtech/jumpscaleX_libs/issues/13
