### ISSUE TITLE
Not able to send locked tokens from account

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/jumpscaleX_libs#149]
I am not able to transfer locked tockens using j.clients.stellar.wallet.transfer. A transaction without locked_untill does work but with locked_untill param this seems not to be working
![image](https://user-images.githubusercontent.com/17977313/78348353-2ee2f900-75a2-11ea-8870-9632bb237d99.png)

**Comment by tobiaschielens** [comment]
As far as I can seem something goes wrong on adding the trustline to the escrow account
![image](https://user-images.githubusercontent.com/17977313/78356987-e8e16180-75b0-11ea-82c0-c250901017a1.png)

**Comment by DylanVerstraete** [comment]
Sending account needs atleast 10 XLM to make a locked token transfer
