### ISSUE TITLE
 Paying with wallet that has zero tft or less amount of tft, should return meaningful message 

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_libs#156]
## Branches
libs, threebot: **unstable_reservation_payments**
other repos: **unstable**
## Environment 
Devnet

## Scenario
1- create wallet with zero tft 
2- create reservation 
3- user should pay for this reservation 

## Actual Result 
```
JSX> res = zos.billing.payout_farmers(wallet2, registered_reservation)                                    
Mon 06 17:56:03 sal/zosv2/billing.py -  35 - payout_farmers                     : EXCEPTION: 
    AttributeError("'Billing' object has no attribute '_log_error'",)
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/code/github/threefoldtech/jumpscaleX_libs/JumpscaleLibs/sal/zosv2/billing.py in payout_farmers
    35    self._log_error(e)
-----------------------------

'Billing' object has no attribute '_log_error'
JSX> res = zos.billing.payout_farmers(wallet2, registered_reservation) 
         res                  ResourceWarning        
```

## Expected Result
Paying with wallet that has zero tft or less amount of tft than required registered reservation amount , should  return message implying that  user's wallet need to be filled up before proceeding

**Comment by DylanVerstraete** [comment]
@john-kheir can you pull and try again? :-)

**Comment by john-kheir** [comment]
working fine now
