### ISSUE TITLE
Create project method in Digital Ocean client

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_libs#18]
- need method for project create in Digitalocean client.

**Comment by serboctor** [comment]
Also, look into the possibility of specifying the project while creating a droplet, and listing the droplets of a certain project.

**Comment by serboctor** [comment]
Added project functionality here https://github.com/threefoldtech/jumpscaleX_libs/commit/b7f85cfc7e5202cd4a747815d1414b16d05f7842

You can create, delete and list projects. If you want to list droplets in a certain project, you can use droplist_list(project_name). If you want to create a droplet in a certain project, you can specify `project_name` in the `droplet_create` function.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
