### ISSUE TITLE
bug in droplet methods in digitalocean client 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_libs#19]
I create a DO client with certain `project_name` argument which is created before and use `droplet_create` method to create a new droplet is created in default project `codescalers`
and when i use `droplets` method it lists all droplets not only droplets which belong to my project

- test_client = j.clients.digitalocean.get(name="test_client", token_="", project_name="DO_client_testing")

- test_client.droplets
```
[<Droplet: 155618078 TF-Gold-ams3-01>, <Droplet: 155618079 TF-Gold-ams3-02>, <Droplet: 155618080 TF-Gold-ams3-03>, <Droplet: 155618081 TF-Gold-ams3-04>, <Droplet: 158177433 dogateway>, <Droplet: 158335428 3bottest>, <Droplet: 159374912 threebot-actortest>, <Droplet: 159515507 threefold.web.grid.tf>, <Droplet: 160093068 testwikis>, <Droplet: 160242306 threebot-wikibot4>, <Droplet: 160386089 threebot-snapshot>, <Droplet: 161213309 manager>, <Droplet: 161228355 router1>, <Droplet: 161228855 router2>, <Droplet: 161228963 router3>, <Droplet: 161909954 test-threebot-testtools>, <Droplet: 162164841 ubuntu-s-1vcpu-1gb-nyc1-01>, <Droplet: 162173754 test-DO-client>]
```

**Comment by serboctor** [comment]
@rkhamis the `project_name` is only used in the client's schema, it's not used anywhere else in the code. Should I just remove it from the schema? I feel that the client shouldn't be linked to just one project anyway.

**Comment by rkhamis** [comment]
@serboctor indeed the project_name is not part of the client, but should be an arg in the methods where the project is filterable.

**Comment by serboctor** [comment]
@rkhamis the droplet object doesn't have any attributes relating to the project. And even the droplet create api of digital ocean doesn't let you specify a project. Instead, they have a project api, which can be used to move the droplet under the project, and each project's resources can be listed from this api. I think the python library we're using doesn't expose any of the project's functionality, but i am already investigating this in this task https://github.com/threefoldtech/jumpscaleX_libs/issues/18 so I'll close this issue and any project-related changes will be done in the other task.
