### ISSUE TITLE
why we use meta in DigitalOcean client shema 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_libs#20]
- we use meta in DigitalOcean client schema, why we need this ??

```
    @url = jumpscale.digitalocean.client
    name** = "" (S)
    token_ = "" (S)
    project_name = "" (S)
    meta = {} (DICT)
    vms = (LO) !jumpscale.digitalocean.vm
```

**Comment by Dina-Abd-Elrahman** [comment]
- also why we need load method in DO client, i think it's the same like get method it's just use to load the client from BCDB.

**Comment by serboctor** [comment]
> also why we need load method in DO client, i think it's the same like get method it's just use to load the client from BCDB.

`load` is a function of the baseclasses, it's not specific to digital ocean. Any client that inherits from `JSconfigBCDB` will have this function and you don't need to worry about it.

**Comment by serboctor** [comment]
> we use meta in DigitalOcean client schema, why we need this ?? 

`meta` is not being used anywhere.

**Comment by serboctor** [comment]
I'll remove the `meta` from the client schema.

**Comment by serboctor** [comment]
https://github.com/threefoldtech/jumpscaleX_libs/commit/7271fc9c0223d46732f6592fc878cbdabd787667
