### ISSUE TITLE
need to update reservation examples docs

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_libs#209]
as ex: minio container reservation example 
https://github.com/threefoldtech/jumpscaleX_libs/tree/development/JumpscaleLibs/sal/zosv2#example--deploy-minio-container
zdb_rid = zos.reservation_register(reservation_storage, j.data.time.epoch+(60*60))
results = zos.reservation_result(zdb_rid)

should be zdb_rid.reservation_id 

and should mention that u should pay first to see results

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
