### ISSUE TITLE
zos SAL: payout_farmer method should check if there is enough found in the wallet before trying to execute the transaction

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_libs#237]
https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/zosv2/billing.py#L12

**Comment by grimpy** [comment]
![image](https://user-images.githubusercontent.com/143869/85992407-2198a780-b9f5-11ea-837a-61b983033f04.png)

**Comment by AhmedHanafy725** [comment]
**Verified**

1- Create new wallet.

![image](https://user-images.githubusercontent.com/41957921/86231317-a967e880-bb92-11ea-8a78-7f8185aac555.png)

2- Try to deploy ubuntu container with the new wallet.

![image](https://user-images.githubusercontent.com/41957921/86231179-6d348800-bb92-11ea-9e37-44a38edc8381.png)

3- Check if there is a transaction happened.

![image](https://user-images.githubusercontent.com/41957921/86231522-fa77dc80-bb92-11ea-85de-fcdea191d1c9.png)
