### ISSUE TITLE
add project name in droplet_all_delete, droplet_all_shutdown and droplets in DO client 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_libs#31]
- need to add project name as an argument in `droplet_all_delete`, `droplet_all_shutdown` and `droplets` methods in DigitalOcean client.

**Comment by alichaddad** [comment]
Done here https://github.com/threefoldtech/jumpscaleX_libs/commit/2be77f5b49212283a4c0280370a6d009dd573e44

You can use `droplets_list` to filter droplets using project name already. Implemented it for `droplet_all_delete` and `droplet_all_shutdown`

**Comment by Dina-Abd-Elrahman** [comment]
- Verified.
