### ISSUE TITLE
Start imap server raise error [development]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_libs#41]
JSX> j.servers.imap.start()      
```                                                                       
Thu 05 12:30:35 /schema/JSXObject.py - 151 - check_empty_indexed_fields         : EXCEPTION: 
    an indexed (sql) field cannot be empty:attributes
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/JumpscaleLibs/servers/mail/imap/imapfactory.py in start
    11    self.get_instance(address, port).serve_forever()
/sandbox/lib/jumpscale/JumpscaleLibs/servers/mail/imap/imapfactory.py in get_instance
    14    models = self.get_models()
/sandbox/lib/jumpscale/JumpscaleLibs/servers/mail/imap/imapfactory.py in get_models
    30    folder.save()
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py in save
    164    self.check_empty_indexed_fields()
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py in check_empty_indexed_fields
    151    raise j.exceptions.Input("an indexed (sql) field cannot be empty:%s" % prop.name, data=self)
-----------------------------

--DATA-----------------------
  ## .email.folder
   - name                : inbox
   - subscribed          : True
   - mtime               : -
   - attributes          :
   - sequences           : {}
-----------------------------

```

**Comment by serboctor** [comment]
Removing the indexing here would stop this error and the server will start. https://github.com/threefoldtech/jumpscaleX_libs/blob/master/JumpscaleLibs/servers/mail/models/jumpscale_email_folder.toml#L5 

However, if any queries depend on the attributes, then those queries will fail. I am not familiar with this server but using a find, I found this which I think depends on the indexing so I am not sure what should be done here.
https://github.com/threefoldtech/jumpscaleX_libs/blob/master/JumpscaleLibs/servers/mail/imap/asimap/user_server.py#L384

**Comment by RafyAmgadBenjamin** [comment]
PR
https://github.com/threefoldtech/jumpscaleX_libs/pull/44

**Comment by hossnys** [comment]
verified on development_fixes 049c8bf4

![image](https://user-images.githubusercontent.com/26298009/70861491-5f415180-1f37-11ea-803f-209c8de159f3.png)

![Screenshot from 2019-12-15 12-34-28](https://user-images.githubusercontent.com/26298009/70861487-52bcf900-1f37-11ea-8ac8-fd127e45d648.png)

**Comment by Dina-Abd-Elrahman** [comment]
the error still exists in development branch, after merge with `development_bugfixes`

**Comment by xmonader** [comment]
> the error still exists in development branch, after merge with `development_bugfixes`

Why moved back after verification on "development_fixes"? why are you verifying on development_bugfixes?

**Comment by RafyAmgadBenjamin** [comment]
PR
https://github.com/threefoldtech/jumpscaleX_libs/pull/47

**Comment by xmonader** [comment]
@Dina-Abd-Elrahman please verify on development branch

**Comment by Dina-Abd-Elrahman** [comment]
@xmonader I mentioned that the error on development branch, which means I verified on it,   I meant it's fixed on `development_budfixes` but when we merge with development it raises the same error again.

**Comment by Dina-Abd-Elrahman** [comment]
now it's fixed, but it raises an error when trying `create_folder` method using `imapclient` in python3

![error](https://user-images.githubusercontent.com/21218053/71321288-eeaead80-24bf-11ea-8a3c-45ccc86cbc0e.png)

**Comment by RafyAmgadBenjamin** [comment]
I have fixed the previous issue:
**PR**
https://github.com/threefoldtech/jumpscaleX_libs/pull/48
![image](https://user-images.githubusercontent.com/46320202/71321717-62ec4f80-24c6-11ea-8f9e-73ea0f2e9910.png)

![image](https://user-images.githubusercontent.com/46320202/71321722-74cdf280-24c6-11ea-9965-535bc0e9d840.png)

**Comment by Dina-Abd-Elrahman** [comment]
- it's working now.
