### ISSUE TITLE
Coredns test need to be independent of required client argument

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_libs#77]
The test need a required client parameters, please make sure it is independent of the client param and make sure the test is passing 

### Test Location 
/sandbox/code/github/threefoldtech/jumpscaleX_libs/JumpscaleLibs/clients/coredns/CoreDNSFactory.py
### Error
```
JSX> j.clients.coredns.test()                                                                        
Thu 13 06:54:53 <stdin>              -   1 - <module>                           : EXCEPTION: 
    TypeError("test() missing 1 required positional argument: 'client'",)
--TRACEBACK------------------
<stdin> in <module>
    1    
-----------------------------

test() missing 1 required positional argument: 'client'

```

**Comment by xmonader** [comment]
disable from tests please https://github.com/threefoldtech/jumpscaleX_libs/blob/0d12209bb40b8ccc38e59945df3e01f617e8dc26/JumpscaleLibs/clients/coredns/CoreDnsClient.py#L18 is an old client.
